Fix #53
linusg/rpi-backlight pull request #54
Opened 2022-09-09 03:10 UTC by apandada1

Added Surface RT support with automatic detection. Fixes #53 

Tested on my Surface RT.

2022-09-09 03:12 UTC, apandada1 commented
Please release a new version (so that Surface users can easily install with pip) when merged.

2022-09-09 08:36 UTC, linusg requested changes

2022-09-09 08:36 UTC, linusg commented on rpi_backlight/__init__.py
> +        ):
```suggestion
        if self._board_type in BoardType.RASPBERRY_P,I BoardType.MICROSOFT_SURFACE_RT):
```

2022-09-09 08:36 UTC, linusg commented on README.md
> +  (look on the display's circuit board to see its version), or as [Surface RT](https://openrt.gitbook.io/open-surfacert/surface-rt/linux/root-filesystem/distros/raspberry-pi-os) running a Linux-based
```suggestion
  (look on the display's circuit board to see its version), or a [**Surface RT**](https://openrt.gitbook.io/open-surfacert/surface-rt/linux/root-filesystem/distros/raspberry-pi-os) running a Linux-based OS
```

2022-09-10 20:41 UTC, apandada1 commented
Done :)

2022-09-13 03:59 UTC, apandada1 commented
Any updates? I am not sure why the GitHub build failed. The software seems to work without an issue.

2022-09-13 11:09 UTC, linusg commented
you didn't run black, click on "Details" next to the red X

2022-09-13 12:06 UTC, apandada1 commented
Oh, I didn't know about black before. Finally, done :)

2022-09-13 12:39 UTC, merged

2022-09-13 14:39 UTC, apandada1 commented
Can you please release a new version and push it to pypi?